<div class="row">
    
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('homesection.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'homesection.index') ? ' active' : ''); ?>"><?php echo e(__('Home')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('custom_page.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'custom_page.index') ? ' active' : ''); ?>"><?php echo e(__('Custom Page')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('features.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'features.index') ? ' active' : ''); ?>"><?php echo e(__('Features')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('discover.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'discover.index') ? ' active' : ''); ?>"><?php echo e(__('Discover')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
<a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('screenshots.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'screenshots.index') ? ' active' : ''); ?>"><?php echo e(__('Screenshots')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('pricing_plan.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'pricing_plan.index') ? ' active' : ''); ?>"><?php echo e(__('Pricing Plan')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('faq.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'faq.index') ? ' active' : ''); ?>"><?php echo e(__('FAQ')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('testimonials.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'testimonials.index') ? ' active' : ''); ?>"><?php echo e(__('Testimonials')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
        <a style=" color: white; padding: 10px; border-radius: 10px; background:#878787;margin-bottom:10px;" href="<?php echo e(route('join_us.index')); ?>" class="list-group-item list-group-item-action border-0 <?php echo e((Request::route()->getName() == 'join_us.index') ? ' active' : ''); ?>"><?php echo e(__('Join Us')); ?> <div class="float-end"><i class="fa fa-chevron-right"></i></div></a>
</div><?php /**PATH C:\xampp\htdocs\rezo2\Modules/LandingPage\Resources/views/layouts/tab.blade.php ENDPATH**/ ?>